name: CombinedForce
main: cc.isotopestudio.CombinedForce.CombinedForce

author: Mars
description: Combined Forces, Inlay Gems
website: http://isotopestudio.cc
version: 3.0
commands:
  inlay:
    description: CombinedForce Command.
    usage: /xq
    aliases: xq
  inlayadd:
    description: CombinedForce Command.
    usage: /xqadd
    aliases: xqadd
  inlaygem:
    description: CombinedForce Command.
    usage: /xqgem
    aliases: xqgem
  outgem:
    description: CombinedForce Command.
    usage: /outgem